# Generated by Django 6.0.3 on 2026-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_specialization_user_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_skills', to='api.specialization'),
        ),
    ]
